/********************************************************************************
** Form generated from reading UI file 'comport.ui'
**
** Created by: Qt User Interface Compiler version 5.4.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_COMPORT_H
#define UI_COMPORT_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLCDNumber>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_comPortClass
{
public:
    QWidget *centralWidget;
    QPushButton *btnSend;
    QLineEdit *txtSend;
    QLabel *labTitle;
    QLabel *labCom;
    QTextEdit *areaSend;
    QFrame *line;
    QFrame *line_2;
    QFrame *line_3;
    QFrame *line_4;
    QFrame *line_5;
    QFrame *line_6;
    QFrame *line_7;
    QFrame *line_8;
    QLabel *labTime;
    QLineEdit *txtTime;
    QFrame *line_9;
    QFrame *line_10;
    QFrame *line_11;
    QFrame *line_12;
    QTextEdit *areaRece;
    QPushButton *btnRStart;
    QPushButton *btnRStop;
    QLabel *labTime_2;
    QLineEdit *txtTime2;
    QFrame *line_13;
    QLabel *labRec;
    QFrame *line_14;
    QFrame *line_15;
    QFrame *line_16;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QComboBox *comPort1;
    QComboBox *comPort2;
    QLabel *labTemper;
    QFrame *line_17;
    QFrame *line_18;
    QFrame *line_19;
    QFrame *line_20;
    QLCDNumber *ledTemper;
    QLabel *labHumidity;
    QLCDNumber *ledHumid;
    QLabel *labLight;
    QLCDNumber *ledLight;
    QComboBox *comType1;
    QComboBox *comType2;
    QLabel *labCoding;
    QLabel *labCoding2;
    QPushButton *btnExit;
    QFrame *line_21;
    QFrame *line_22;
    QFrame *line_23;
    QFrame *line_24;
    QLabel *labVibration;
    QLCDNumber *ledVibration;
    QLabel *labSmoke;
    QLCDNumber *ledSmoke;
    QLabel *labInfrared;
    QLCDNumber *ledInfrared;
    QFrame *line_25;
    QFrame *line_26;
    QFrame *line_27;
    QFrame *line_28;
    QLabel *labInTouche;
    QLCDNumber *ledTouch;
    QLabel *labInWave;
    QLCDNumber *ledWave;
    QPushButton *btnRunType1;
    QPushButton *btnRunType0;
    QPushButton *btnRunType2;
    QComboBox *comRate;
    QLabel *labCom_2;
    QLabel *labCom_3;
    QComboBox *comDataBits;
    QFrame *line_29;
    QFrame *line_30;
    QFrame *line_31;
    QFrame *line_32;
    QPushButton *btnExit_2;
    QFrame *line_33;
    QFrame *line_34;
    QFrame *line_35;
    QFrame *line_36;
    QFrame *line_37;
    QFrame *line_38;
    QFrame *line_39;
    QFrame *line_40;
    QLabel *labLight_2;
    QLabel *labLight_3;
    QSlider *sildLight;
    QFrame *line_41;
    QFrame *line_42;
    QFrame *line_43;
    QFrame *line_44;
    QFrame *line_45;
    QFrame *line_46;
    QFrame *line_47;
    QFrame *line_48;
    QLabel *labManStatus;
    QLabel *labLight_5;
    QPushButton *btnRunType3;
    QCheckBox *checkHeat;
    QCheckBox *checkLight;
    QCheckBox *checkSmoke;

    void setupUi(QMainWindow *comPortClass)
    {
        if (comPortClass->objectName().isEmpty())
            comPortClass->setObjectName(QStringLiteral("comPortClass"));
        comPortClass->resize(990, 620);
        centralWidget = new QWidget(comPortClass);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        btnSend = new QPushButton(centralWidget);
        btnSend->setObjectName(QStringLiteral("btnSend"));
        btnSend->setGeometry(QRect(480, 310, 61, 31));
        QFont font;
        font.setFamily(QStringLiteral("SAO UI"));
        font.setPointSize(14);
        btnSend->setFont(font);
        txtSend = new QLineEdit(centralWidget);
        txtSend->setObjectName(QStringLiteral("txtSend"));
        txtSend->setGeometry(QRect(30, 310, 441, 31));
        QFont font1;
        font1.setFamily(QString::fromUtf8("\345\256\213\344\275\223"));
        font1.setPointSize(11);
        txtSend->setFont(font1);
        txtSend->setLayoutDirection(Qt::LeftToRight);
        txtSend->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        labTitle = new QLabel(centralWidget);
        labTitle->setObjectName(QStringLiteral("labTitle"));
        labTitle->setGeometry(QRect(200, 20, 651, 81));
        QFont font2;
        font2.setFamily(QStringLiteral("SAO UI"));
        font2.setPointSize(36);
        font2.setBold(false);
        font2.setWeight(50);
        labTitle->setFont(font2);
        labTitle->setLayoutDirection(Qt::LeftToRight);
        labTitle->setFrameShadow(QFrame::Raised);
        labTitle->setAlignment(Qt::AlignCenter);
        labCom = new QLabel(centralWidget);
        labCom->setObjectName(QStringLiteral("labCom"));
        labCom->setGeometry(QRect(20, 120, 91, 41));
        QFont font3;
        font3.setFamily(QStringLiteral("SAO UI"));
        font3.setPointSize(14);
        font3.setBold(false);
        font3.setWeight(50);
        labCom->setFont(font3);
        labCom->setFrameShadow(QFrame::Raised);
        labCom->setAlignment(Qt::AlignCenter);
        areaSend = new QTextEdit(centralWidget);
        areaSend->setObjectName(QStringLiteral("areaSend"));
        areaSend->setGeometry(QRect(30, 190, 511, 101));
        areaSend->setFont(font1);
        areaSend->setFrameShadow(QFrame::Raised);
        line = new QFrame(centralWidget);
        line->setObjectName(QStringLiteral("line"));
        line->setGeometry(QRect(20, 160, 531, 20));
        QFont font4;
        font4.setPointSize(14);
        line->setFont(font4);
        line->setFrameShadow(QFrame::Raised);
        line->setFrameShape(QFrame::HLine);
        line_2 = new QFrame(centralWidget);
        line_2->setObjectName(QStringLiteral("line_2"));
        line_2->setGeometry(QRect(20, 340, 531, 20));
        line_2->setFont(font4);
        line_2->setFrameShadow(QFrame::Raised);
        line_2->setFrameShape(QFrame::HLine);
        line_3 = new QFrame(centralWidget);
        line_3->setObjectName(QStringLiteral("line_3"));
        line_3->setGeometry(QRect(10, 180, 20, 171));
        line_3->setFont(font4);
        line_3->setFrameShadow(QFrame::Raised);
        line_3->setFrameShape(QFrame::VLine);
        line_4 = new QFrame(centralWidget);
        line_4->setObjectName(QStringLiteral("line_4"));
        line_4->setGeometry(QRect(540, 180, 20, 171));
        line_4->setFont(font4);
        line_4->setFrameShadow(QFrame::Raised);
        line_4->setFrameShape(QFrame::VLine);
        line_5 = new QFrame(centralWidget);
        line_5->setObjectName(QStringLiteral("line_5"));
        line_5->setGeometry(QRect(20, 110, 531, 20));
        line_5->setFont(font4);
        line_5->setFrameShadow(QFrame::Raised);
        line_5->setFrameShape(QFrame::HLine);
        line_6 = new QFrame(centralWidget);
        line_6->setObjectName(QStringLiteral("line_6"));
        line_6->setGeometry(QRect(20, 170, 531, 20));
        line_6->setFont(font4);
        line_6->setFrameShadow(QFrame::Raised);
        line_6->setFrameShape(QFrame::HLine);
        line_7 = new QFrame(centralWidget);
        line_7->setObjectName(QStringLiteral("line_7"));
        line_7->setGeometry(QRect(10, 120, 20, 51));
        line_7->setFont(font4);
        line_7->setFrameShadow(QFrame::Raised);
        line_7->setFrameShape(QFrame::VLine);
        line_8 = new QFrame(centralWidget);
        line_8->setObjectName(QStringLiteral("line_8"));
        line_8->setGeometry(QRect(540, 120, 20, 51));
        line_8->setFont(font4);
        line_8->setFrameShadow(QFrame::Raised);
        line_8->setFrameShape(QFrame::VLine);
        labTime = new QLabel(centralWidget);
        labTime->setObjectName(QStringLiteral("labTime"));
        labTime->setGeometry(QRect(200, 120, 81, 41));
        labTime->setFont(font3);
        labTime->setFrameShadow(QFrame::Raised);
        labTime->setAlignment(Qt::AlignCenter);
        txtTime = new QLineEdit(centralWidget);
        txtTime->setObjectName(QStringLiteral("txtTime"));
        txtTime->setGeometry(QRect(290, 125, 71, 31));
        txtTime->setFont(font3);
        line_9 = new QFrame(centralWidget);
        line_9->setObjectName(QStringLiteral("line_9"));
        line_9->setGeometry(QRect(20, 590, 531, 20));
        line_9->setFont(font4);
        line_9->setFrameShadow(QFrame::Raised);
        line_9->setFrameShape(QFrame::HLine);
        line_10 = new QFrame(centralWidget);
        line_10->setObjectName(QStringLiteral("line_10"));
        line_10->setGeometry(QRect(20, 400, 531, 20));
        line_10->setFont(font4);
        line_10->setFrameShadow(QFrame::Raised);
        line_10->setFrameShape(QFrame::HLine);
        line_11 = new QFrame(centralWidget);
        line_11->setObjectName(QStringLiteral("line_11"));
        line_11->setGeometry(QRect(540, 430, 20, 171));
        line_11->setFont(font4);
        line_11->setFrameShadow(QFrame::Raised);
        line_11->setFrameShape(QFrame::VLine);
        line_12 = new QFrame(centralWidget);
        line_12->setObjectName(QStringLiteral("line_12"));
        line_12->setGeometry(QRect(10, 430, 20, 171));
        line_12->setFont(font4);
        line_12->setFrameShadow(QFrame::Raised);
        line_12->setFrameShape(QFrame::VLine);
        areaRece = new QTextEdit(centralWidget);
        areaRece->setObjectName(QStringLiteral("areaRece"));
        areaRece->setGeometry(QRect(30, 440, 501, 111));
        areaRece->setFont(font1);
        areaRece->setFrameShadow(QFrame::Raised);
        btnRStart = new QPushButton(centralWidget);
        btnRStart->setObjectName(QStringLiteral("btnRStart"));
        btnRStart->setGeometry(QRect(150, 560, 91, 31));
        btnRStart->setFont(font);
        btnRStop = new QPushButton(centralWidget);
        btnRStop->setObjectName(QStringLiteral("btnRStop"));
        btnRStop->setGeometry(QRect(300, 560, 91, 31));
        btnRStop->setFont(font);
        labTime_2 = new QLabel(centralWidget);
        labTime_2->setObjectName(QStringLiteral("labTime_2"));
        labTime_2->setGeometry(QRect(210, 360, 91, 41));
        labTime_2->setFont(font3);
        labTime_2->setFrameShadow(QFrame::Raised);
        labTime_2->setAlignment(Qt::AlignCenter);
        txtTime2 = new QLineEdit(centralWidget);
        txtTime2->setObjectName(QStringLiteral("txtTime2"));
        txtTime2->setGeometry(QRect(300, 365, 71, 31));
        txtTime2->setFont(font);
        line_13 = new QFrame(centralWidget);
        line_13->setObjectName(QStringLiteral("line_13"));
        line_13->setGeometry(QRect(20, 420, 531, 20));
        line_13->setFont(font4);
        line_13->setFrameShadow(QFrame::Raised);
        line_13->setFrameShape(QFrame::HLine);
        labRec = new QLabel(centralWidget);
        labRec->setObjectName(QStringLiteral("labRec"));
        labRec->setGeometry(QRect(30, 360, 101, 41));
        labRec->setFont(font3);
        labRec->setFrameShadow(QFrame::Raised);
        labRec->setAlignment(Qt::AlignCenter);
        line_14 = new QFrame(centralWidget);
        line_14->setObjectName(QStringLiteral("line_14"));
        line_14->setGeometry(QRect(10, 360, 20, 51));
        line_14->setFont(font4);
        line_14->setFrameShadow(QFrame::Raised);
        line_14->setFrameShape(QFrame::VLine);
        line_15 = new QFrame(centralWidget);
        line_15->setObjectName(QStringLiteral("line_15"));
        line_15->setGeometry(QRect(540, 360, 20, 51));
        line_15->setFont(font4);
        line_15->setFrameShadow(QFrame::Raised);
        line_15->setFrameShape(QFrame::VLine);
        line_16 = new QFrame(centralWidget);
        line_16->setObjectName(QStringLiteral("line_16"));
        line_16->setGeometry(QRect(20, 350, 531, 20));
        line_16->setFont(font4);
        line_16->setFrameShadow(QFrame::Raised);
        line_16->setFrameShape(QFrame::HLine);
        label = new QLabel(centralWidget);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(-10, 0, 1001, 10));
        QPalette palette;
        QBrush brush(QColor(255, 255, 255, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(0, 0, 0, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette.setBrush(QPalette::Active, QPalette::Light, brush1);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush1);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush1);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush1);
        QBrush brush2(QColor(255, 255, 220, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        label->setPalette(palette);
        label->setFont(font4);
        label->setAutoFillBackground(true);
        label->setFrameShadow(QFrame::Raised);
        label_2 = new QLabel(centralWidget);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(0, 610, 991, 16));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Midlight, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush);
        palette1.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette1.setBrush(QPalette::Active, QPalette::AlternateBase, brush1);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        label_2->setPalette(palette1);
        label_2->setFont(font4);
        label_2->setAutoFillBackground(true);
        label_2->setFrameShadow(QFrame::Raised);
        label_3 = new QLabel(centralWidget);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(0, 0, 10, 631));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette2.setBrush(QPalette::Active, QPalette::Light, brush1);
        palette2.setBrush(QPalette::Active, QPalette::Midlight, brush1);
        palette2.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette2.setBrush(QPalette::Active, QPalette::Mid, brush1);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush);
        palette2.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette2.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette2.setBrush(QPalette::Active, QPalette::AlternateBase, brush1);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Light, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Midlight, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Mid, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Light, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Midlight, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Mid, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        label_3->setPalette(palette2);
        label_3->setFont(font4);
        label_3->setAutoFillBackground(true);
        label_3->setFrameShadow(QFrame::Raised);
        label_4 = new QLabel(centralWidget);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(980, 0, 16, 641));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Light, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Midlight, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Mid, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Text, brush);
        palette3.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette3.setBrush(QPalette::Active, QPalette::AlternateBase, brush1);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Light, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Midlight, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Mid, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Light, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Midlight, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Mid, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        label_4->setPalette(palette3);
        label_4->setFont(font4);
        label_4->setAutoFillBackground(true);
        label_4->setFrameShadow(QFrame::Raised);
        comPort1 = new QComboBox(centralWidget);
        comPort1->setObjectName(QStringLiteral("comPort1"));
        comPort1->setGeometry(QRect(110, 125, 81, 31));
        QFont font5;
        font5.setFamily(QStringLiteral("SAO UI"));
        font5.setPointSize(14);
        font5.setBold(true);
        font5.setWeight(75);
        comPort1->setFont(font5);
        comPort1->setMaxVisibleItems(10);
        comPort2 = new QComboBox(centralWidget);
        comPort2->setObjectName(QStringLiteral("comPort2"));
        comPort2->setGeometry(QRect(130, 365, 81, 31));
        comPort2->setFont(font5);
        labTemper = new QLabel(centralWidget);
        labTemper->setObjectName(QStringLiteral("labTemper"));
        labTemper->setGeometry(QRect(580, 140, 111, 31));
        labTemper->setFont(font3);
        labTemper->setFrameShadow(QFrame::Raised);
        labTemper->setAlignment(Qt::AlignCenter);
        line_17 = new QFrame(centralWidget);
        line_17->setObjectName(QStringLiteral("line_17"));
        line_17->setGeometry(QRect(570, 110, 221, 20));
        line_17->setFont(font4);
        line_17->setFrameShadow(QFrame::Raised);
        line_17->setFrameShape(QFrame::HLine);
        line_18 = new QFrame(centralWidget);
        line_18->setObjectName(QStringLiteral("line_18"));
        line_18->setGeometry(QRect(570, 590, 221, 20));
        line_18->setFont(font4);
        line_18->setFrameShadow(QFrame::Raised);
        line_18->setFrameShape(QFrame::HLine);
        line_19 = new QFrame(centralWidget);
        line_19->setObjectName(QStringLiteral("line_19"));
        line_19->setGeometry(QRect(560, 120, 20, 481));
        line_19->setFont(font4);
        line_19->setFrameShadow(QFrame::Raised);
        line_19->setFrameShape(QFrame::VLine);
        line_20 = new QFrame(centralWidget);
        line_20->setObjectName(QStringLiteral("line_20"));
        line_20->setGeometry(QRect(780, 120, 20, 481));
        line_20->setFont(font4);
        line_20->setFrameShadow(QFrame::Raised);
        line_20->setFrameShape(QFrame::VLine);
        ledTemper = new QLCDNumber(centralWidget);
        ledTemper->setObjectName(QStringLiteral("ledTemper"));
        ledTemper->setGeometry(QRect(710, 140, 71, 31));
        ledTemper->setFont(font4);
        ledTemper->setFrameShadow(QFrame::Raised);
        ledTemper->setSmallDecimalPoint(false);
        ledTemper->setDigitCount(5);
        labHumidity = new QLabel(centralWidget);
        labHumidity->setObjectName(QStringLiteral("labHumidity"));
        labHumidity->setGeometry(QRect(580, 190, 91, 31));
        labHumidity->setFont(font3);
        labHumidity->setFrameShadow(QFrame::Raised);
        labHumidity->setAlignment(Qt::AlignCenter);
        ledHumid = new QLCDNumber(centralWidget);
        ledHumid->setObjectName(QStringLiteral("ledHumid"));
        ledHumid->setGeometry(QRect(710, 190, 71, 31));
        ledHumid->setFont(font4);
        ledHumid->setFrameShadow(QFrame::Raised);
        ledHumid->setDigitCount(5);
        labLight = new QLabel(centralWidget);
        labLight->setObjectName(QStringLiteral("labLight"));
        labLight->setGeometry(QRect(590, 240, 71, 31));
        labLight->setFont(font3);
        labLight->setFrameShadow(QFrame::Raised);
        labLight->setAlignment(Qt::AlignCenter);
        ledLight = new QLCDNumber(centralWidget);
        ledLight->setObjectName(QStringLiteral("ledLight"));
        ledLight->setGeometry(QRect(710, 240, 71, 31));
        ledLight->setFont(font4);
        ledLight->setFrameShadow(QFrame::Raised);
        ledLight->setDigitCount(5);
        comType1 = new QComboBox(centralWidget);
        comType1->setObjectName(QStringLiteral("comType1"));
        comType1->setGeometry(QRect(460, 125, 81, 31));
        comType1->setFont(font5);
        comType2 = new QComboBox(centralWidget);
        comType2->setObjectName(QStringLiteral("comType2"));
        comType2->setGeometry(QRect(450, 365, 81, 31));
        comType2->setFont(font5);
        labCoding = new QLabel(centralWidget);
        labCoding->setObjectName(QStringLiteral("labCoding"));
        labCoding->setGeometry(QRect(370, 120, 81, 41));
        labCoding->setFont(font3);
        labCoding->setFrameShadow(QFrame::Raised);
        labCoding->setAlignment(Qt::AlignCenter);
        labCoding2 = new QLabel(centralWidget);
        labCoding2->setObjectName(QStringLiteral("labCoding2"));
        labCoding2->setGeometry(QRect(380, 360, 61, 41));
        labCoding2->setFont(font3);
        labCoding2->setFrameShadow(QFrame::Raised);
        labCoding2->setAlignment(Qt::AlignCenter);
        btnExit = new QPushButton(centralWidget);
        btnExit->setObjectName(QStringLiteral("btnExit"));
        btnExit->setGeometry(QRect(880, 30, 81, 31));
        btnExit->setFont(font);
        line_21 = new QFrame(centralWidget);
        line_21->setObjectName(QStringLiteral("line_21"));
        line_21->setGeometry(QRect(790, 120, 20, 221));
        line_21->setFont(font4);
        line_21->setFrameShadow(QFrame::Raised);
        line_21->setFrameShape(QFrame::VLine);
        line_22 = new QFrame(centralWidget);
        line_22->setObjectName(QStringLiteral("line_22"));
        line_22->setGeometry(QRect(800, 330, 171, 20));
        line_22->setFont(font4);
        line_22->setFrameShadow(QFrame::Raised);
        line_22->setFrameShape(QFrame::HLine);
        line_23 = new QFrame(centralWidget);
        line_23->setObjectName(QStringLiteral("line_23"));
        line_23->setGeometry(QRect(870, 100, 101, 20));
        line_23->setFont(font4);
        line_23->setFrameShadow(QFrame::Raised);
        line_23->setFrameShape(QFrame::HLine);
        line_24 = new QFrame(centralWidget);
        line_24->setObjectName(QStringLiteral("line_24"));
        line_24->setGeometry(QRect(960, 120, 20, 221));
        line_24->setFont(font4);
        line_24->setFrameShadow(QFrame::Raised);
        line_24->setFrameShape(QFrame::VLine);
        labVibration = new QLabel(centralWidget);
        labVibration->setObjectName(QStringLiteral("labVibration"));
        labVibration->setGeometry(QRect(590, 290, 81, 31));
        labVibration->setFont(font3);
        labVibration->setFrameShadow(QFrame::Raised);
        labVibration->setAlignment(Qt::AlignCenter);
        ledVibration = new QLCDNumber(centralWidget);
        ledVibration->setObjectName(QStringLiteral("ledVibration"));
        ledVibration->setGeometry(QRect(710, 290, 71, 31));
        ledVibration->setFont(font4);
        ledVibration->setFrameShadow(QFrame::Raised);
        ledVibration->setDigitCount(5);
        ledVibration->setMode(QLCDNumber::Dec);
        labSmoke = new QLabel(centralWidget);
        labSmoke->setObjectName(QStringLiteral("labSmoke"));
        labSmoke->setGeometry(QRect(590, 340, 71, 31));
        labSmoke->setFont(font3);
        labSmoke->setFrameShadow(QFrame::Raised);
        labSmoke->setAlignment(Qt::AlignCenter);
        ledSmoke = new QLCDNumber(centralWidget);
        ledSmoke->setObjectName(QStringLiteral("ledSmoke"));
        ledSmoke->setGeometry(QRect(710, 340, 71, 31));
        ledSmoke->setFont(font4);
        ledSmoke->setFrameShadow(QFrame::Raised);
        ledSmoke->setDigitCount(5);
        ledSmoke->setMode(QLCDNumber::Dec);
        labInfrared = new QLabel(centralWidget);
        labInfrared->setObjectName(QStringLiteral("labInfrared"));
        labInfrared->setGeometry(QRect(590, 390, 71, 31));
        labInfrared->setFont(font3);
        labInfrared->setFrameShadow(QFrame::Raised);
        labInfrared->setAlignment(Qt::AlignCenter);
        ledInfrared = new QLCDNumber(centralWidget);
        ledInfrared->setObjectName(QStringLiteral("ledInfrared"));
        ledInfrared->setGeometry(QRect(710, 390, 71, 31));
        ledInfrared->setFont(font4);
        ledInfrared->setFrameShadow(QFrame::Raised);
        ledInfrared->setDigitCount(5);
        ledInfrared->setMode(QLCDNumber::Dec);
        line_25 = new QFrame(centralWidget);
        line_25->setObjectName(QStringLiteral("line_25"));
        line_25->setGeometry(QRect(800, 430, 171, 20));
        line_25->setFont(font4);
        line_25->setFrameShadow(QFrame::Raised);
        line_25->setFrameShape(QFrame::HLine);
        line_26 = new QFrame(centralWidget);
        line_26->setObjectName(QStringLiteral("line_26"));
        line_26->setGeometry(QRect(800, 350, 171, 20));
        line_26->setFont(font4);
        line_26->setFrameShadow(QFrame::Raised);
        line_26->setFrameShape(QFrame::HLine);
        line_27 = new QFrame(centralWidget);
        line_27->setObjectName(QStringLiteral("line_27"));
        line_27->setGeometry(QRect(960, 360, 20, 81));
        line_27->setFont(font4);
        line_27->setFrameShadow(QFrame::Raised);
        line_27->setFrameShape(QFrame::VLine);
        line_28 = new QFrame(centralWidget);
        line_28->setObjectName(QStringLiteral("line_28"));
        line_28->setGeometry(QRect(790, 360, 20, 81));
        line_28->setFont(font4);
        line_28->setFrameShadow(QFrame::Raised);
        line_28->setFrameShape(QFrame::VLine);
        labInTouche = new QLabel(centralWidget);
        labInTouche->setObjectName(QStringLiteral("labInTouche"));
        labInTouche->setGeometry(QRect(590, 440, 71, 31));
        labInTouche->setFont(font3);
        labInTouche->setFrameShadow(QFrame::Raised);
        labInTouche->setAlignment(Qt::AlignCenter);
        ledTouch = new QLCDNumber(centralWidget);
        ledTouch->setObjectName(QStringLiteral("ledTouch"));
        ledTouch->setGeometry(QRect(710, 440, 71, 31));
        ledTouch->setFont(font4);
        ledTouch->setFrameShadow(QFrame::Raised);
        ledTouch->setDigitCount(5);
        ledTouch->setMode(QLCDNumber::Dec);
        labInWave = new QLabel(centralWidget);
        labInWave->setObjectName(QStringLiteral("labInWave"));
        labInWave->setGeometry(QRect(590, 490, 71, 31));
        labInWave->setFont(font3);
        labInWave->setFrameShadow(QFrame::Raised);
        labInWave->setAlignment(Qt::AlignCenter);
        ledWave = new QLCDNumber(centralWidget);
        ledWave->setObjectName(QStringLiteral("ledWave"));
        ledWave->setGeometry(QRect(710, 490, 71, 31));
        ledWave->setFont(font4);
        ledWave->setFrameShadow(QFrame::Raised);
        ledWave->setDigitCount(5);
        ledWave->setMode(QLCDNumber::Dec);
        btnRunType1 = new QPushButton(centralWidget);
        btnRunType1->setObjectName(QStringLiteral("btnRunType1"));
        btnRunType1->setGeometry(QRect(840, 130, 121, 41));
        btnRunType1->setFont(font);
        btnRunType0 = new QPushButton(centralWidget);
        btnRunType0->setObjectName(QStringLiteral("btnRunType0"));
        btnRunType0->setGeometry(QRect(840, 300, 121, 31));
        btnRunType0->setFont(font);
        btnRunType2 = new QPushButton(centralWidget);
        btnRunType2->setObjectName(QStringLiteral("btnRunType2"));
        btnRunType2->setGeometry(QRect(840, 190, 121, 41));
        btnRunType2->setFont(font);
        comRate = new QComboBox(centralWidget);
        comRate->setObjectName(QStringLiteral("comRate"));
        comRate->setGeometry(QRect(90, 30, 91, 31));
        comRate->setFont(font5);
        comRate->setMaxVisibleItems(10);
        labCom_2 = new QLabel(centralWidget);
        labCom_2->setObjectName(QStringLiteral("labCom_2"));
        labCom_2->setGeometry(QRect(30, 30, 61, 31));
        labCom_2->setFont(font3);
        labCom_2->setFrameShadow(QFrame::Raised);
        labCom_2->setAlignment(Qt::AlignCenter);
        labCom_3 = new QLabel(centralWidget);
        labCom_3->setObjectName(QStringLiteral("labCom_3"));
        labCom_3->setGeometry(QRect(20, 70, 91, 31));
        labCom_3->setFont(font3);
        labCom_3->setFrameShadow(QFrame::Raised);
        labCom_3->setAlignment(Qt::AlignCenter);
        comDataBits = new QComboBox(centralWidget);
        comDataBits->setObjectName(QStringLiteral("comDataBits"));
        comDataBits->setGeometry(QRect(120, 70, 61, 31));
        comDataBits->setFont(font5);
        comDataBits->setMaxVisibleItems(10);
        line_29 = new QFrame(centralWidget);
        line_29->setObjectName(QStringLiteral("line_29"));
        line_29->setGeometry(QRect(20, 10, 171, 20));
        line_29->setFont(font4);
        line_29->setFrameShadow(QFrame::Raised);
        line_29->setFrameShape(QFrame::HLine);
        line_30 = new QFrame(centralWidget);
        line_30->setObjectName(QStringLiteral("line_30"));
        line_30->setGeometry(QRect(20, 100, 171, 20));
        line_30->setFont(font4);
        line_30->setFrameShadow(QFrame::Raised);
        line_30->setFrameShape(QFrame::HLine);
        line_31 = new QFrame(centralWidget);
        line_31->setObjectName(QStringLiteral("line_31"));
        line_31->setGeometry(QRect(10, 20, 20, 91));
        line_31->setFont(font4);
        line_31->setFrameShadow(QFrame::Raised);
        line_31->setFrameShape(QFrame::VLine);
        line_32 = new QFrame(centralWidget);
        line_32->setObjectName(QStringLiteral("line_32"));
        line_32->setGeometry(QRect(180, 20, 20, 91));
        line_32->setFont(font4);
        line_32->setFrameShadow(QFrame::Raised);
        line_32->setFrameShape(QFrame::VLine);
        btnExit_2 = new QPushButton(centralWidget);
        btnExit_2->setObjectName(QStringLiteral("btnExit_2"));
        btnExit_2->setGeometry(QRect(880, 70, 81, 31));
        btnExit_2->setFont(font);
        line_33 = new QFrame(centralWidget);
        line_33->setObjectName(QStringLiteral("line_33"));
        line_33->setGeometry(QRect(960, 20, 20, 91));
        line_33->setFont(font4);
        line_33->setFrameShadow(QFrame::Raised);
        line_33->setFrameShape(QFrame::VLine);
        line_34 = new QFrame(centralWidget);
        line_34->setObjectName(QStringLiteral("line_34"));
        line_34->setGeometry(QRect(870, 10, 101, 20));
        line_34->setFont(font4);
        line_34->setFrameShadow(QFrame::Raised);
        line_34->setFrameShape(QFrame::HLine);
        line_35 = new QFrame(centralWidget);
        line_35->setObjectName(QStringLiteral("line_35"));
        line_35->setGeometry(QRect(800, 110, 171, 20));
        line_35->setFont(font4);
        line_35->setFrameShadow(QFrame::Raised);
        line_35->setFrameShape(QFrame::HLine);
        line_36 = new QFrame(centralWidget);
        line_36->setObjectName(QStringLiteral("line_36"));
        line_36->setGeometry(QRect(860, 20, 20, 91));
        line_36->setFont(font4);
        line_36->setFrameShadow(QFrame::Raised);
        line_36->setFrameShape(QFrame::VLine);
        line_37 = new QFrame(centralWidget);
        line_37->setObjectName(QStringLiteral("line_37"));
        line_37->setGeometry(QRect(840, 20, 20, 91));
        line_37->setFont(font4);
        line_37->setFrameShadow(QFrame::Raised);
        line_37->setFrameShape(QFrame::VLine);
        line_38 = new QFrame(centralWidget);
        line_38->setObjectName(QStringLiteral("line_38"));
        line_38->setGeometry(QRect(200, 10, 651, 20));
        line_38->setFont(font4);
        line_38->setFrameShadow(QFrame::Raised);
        line_38->setFrameShape(QFrame::HLine);
        line_39 = new QFrame(centralWidget);
        line_39->setObjectName(QStringLiteral("line_39"));
        line_39->setGeometry(QRect(200, 100, 651, 20));
        line_39->setFont(font4);
        line_39->setFrameShadow(QFrame::Raised);
        line_39->setFrameShape(QFrame::HLine);
        line_40 = new QFrame(centralWidget);
        line_40->setObjectName(QStringLiteral("line_40"));
        line_40->setGeometry(QRect(190, 20, 20, 91));
        line_40->setFont(font4);
        line_40->setFrameShadow(QFrame::Raised);
        line_40->setFrameShape(QFrame::VLine);
        labLight_2 = new QLabel(centralWidget);
        labLight_2->setObjectName(QStringLiteral("labLight_2"));
        labLight_2->setGeometry(QRect(840, 360, 81, 31));
        labLight_2->setFont(font3);
        labLight_2->setFrameShadow(QFrame::Raised);
        labLight_2->setAlignment(Qt::AlignCenter);
        labLight_3 = new QLabel(centralWidget);
        labLight_3->setObjectName(QStringLiteral("labLight_3"));
        labLight_3->setGeometry(QRect(840, 460, 71, 31));
        labLight_3->setFont(font3);
        labLight_3->setFrameShadow(QFrame::Raised);
        labLight_3->setAlignment(Qt::AlignCenter);
        sildLight = new QSlider(centralWidget);
        sildLight->setObjectName(QStringLiteral("sildLight"));
        sildLight->setGeometry(QRect(820, 500, 131, 22));
        sildLight->setOrientation(Qt::Horizontal);
        line_41 = new QFrame(centralWidget);
        line_41->setObjectName(QStringLiteral("line_41"));
        line_41->setGeometry(QRect(960, 460, 20, 71));
        line_41->setFont(font4);
        line_41->setFrameShadow(QFrame::Raised);
        line_41->setFrameShape(QFrame::VLine);
        line_42 = new QFrame(centralWidget);
        line_42->setObjectName(QStringLiteral("line_42"));
        line_42->setGeometry(QRect(800, 450, 171, 20));
        line_42->setFont(font4);
        line_42->setFrameShadow(QFrame::Raised);
        line_42->setFrameShape(QFrame::HLine);
        line_43 = new QFrame(centralWidget);
        line_43->setObjectName(QStringLiteral("line_43"));
        line_43->setGeometry(QRect(800, 520, 171, 20));
        line_43->setFont(font4);
        line_43->setFrameShadow(QFrame::Raised);
        line_43->setFrameShape(QFrame::HLine);
        line_44 = new QFrame(centralWidget);
        line_44->setObjectName(QStringLiteral("line_44"));
        line_44->setGeometry(QRect(790, 460, 20, 71));
        line_44->setFont(font4);
        line_44->setFrameShadow(QFrame::Raised);
        line_44->setFrameShape(QFrame::VLine);
        line_45 = new QFrame(centralWidget);
        line_45->setObjectName(QStringLiteral("line_45"));
        line_45->setGeometry(QRect(800, 590, 171, 20));
        line_45->setFont(font4);
        line_45->setFrameShadow(QFrame::Raised);
        line_45->setFrameShape(QFrame::HLine);
        line_46 = new QFrame(centralWidget);
        line_46->setObjectName(QStringLiteral("line_46"));
        line_46->setGeometry(QRect(960, 540, 20, 61));
        line_46->setFont(font4);
        line_46->setFrameShadow(QFrame::Raised);
        line_46->setFrameShape(QFrame::VLine);
        line_47 = new QFrame(centralWidget);
        line_47->setObjectName(QStringLiteral("line_47"));
        line_47->setGeometry(QRect(790, 540, 20, 61));
        line_47->setFont(font4);
        line_47->setFrameShadow(QFrame::Raised);
        line_47->setFrameShape(QFrame::VLine);
        line_48 = new QFrame(centralWidget);
        line_48->setObjectName(QStringLiteral("line_48"));
        line_48->setGeometry(QRect(800, 530, 171, 20));
        line_48->setFont(font4);
        line_48->setFrameShadow(QFrame::Raised);
        line_48->setFrameShape(QFrame::HLine);
        labManStatus = new QLabel(centralWidget);
        labManStatus->setObjectName(QStringLiteral("labManStatus"));
        labManStatus->setGeometry(QRect(800, 400, 171, 41));
        labManStatus->setFont(font3);
        labManStatus->setFrameShadow(QFrame::Raised);
        labManStatus->setAlignment(Qt::AlignCenter);
        labLight_5 = new QLabel(centralWidget);
        labLight_5->setObjectName(QStringLiteral("labLight_5"));
        labLight_5->setGeometry(QRect(810, 550, 151, 41));
        labLight_5->setFont(font3);
        labLight_5->setFrameShadow(QFrame::Raised);
        labLight_5->setAlignment(Qt::AlignCenter);
        btnRunType3 = new QPushButton(centralWidget);
        btnRunType3->setObjectName(QStringLiteral("btnRunType3"));
        btnRunType3->setGeometry(QRect(840, 250, 121, 41));
        btnRunType3->setFont(font);
        checkHeat = new QCheckBox(centralWidget);
        checkHeat->setObjectName(QStringLiteral("checkHeat"));
        checkHeat->setGeometry(QRect(810, 140, 16, 19));
        checkLight = new QCheckBox(centralWidget);
        checkLight->setObjectName(QStringLiteral("checkLight"));
        checkLight->setGeometry(QRect(810, 200, 16, 19));
        checkSmoke = new QCheckBox(centralWidget);
        checkSmoke->setObjectName(QStringLiteral("checkSmoke"));
        checkSmoke->setGeometry(QRect(810, 260, 16, 19));
        comPortClass->setCentralWidget(centralWidget);

        retranslateUi(comPortClass);

        QMetaObject::connectSlotsByName(comPortClass);
    } // setupUi

    void retranslateUi(QMainWindow *comPortClass)
    {
        comPortClass->setWindowTitle(QApplication::translate("comPortClass", "comPort", 0));
        btnSend->setText(QApplication::translate("comPortClass", "Send", 0));
        txtSend->setText(QApplication::translate("comPortClass", "Please Inpu your send message!", 0));
        labTitle->setText(QApplication::translate("comPortClass", "serial communication software", 0));
        labCom->setText(QApplication::translate("comPortClass", "Send port", 0));
        areaSend->setHtml(QApplication::translate("comPortClass", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'\345\256\213\344\275\223'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", 0));
        labTime->setText(QApplication::translate("comPortClass", "Wait Time", 0));
        txtTime->setText(QApplication::translate("comPortClass", "1000", 0));
        areaRece->setHtml(QApplication::translate("comPortClass", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'\345\256\213\344\275\223'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", 0));
        btnRStart->setText(QApplication::translate("comPortClass", "Start", 0));
        btnRStop->setText(QApplication::translate("comPortClass", "Stop", 0));
        labTime_2->setText(QApplication::translate("comPortClass", "Wait Time", 0));
        txtTime2->setText(QApplication::translate("comPortClass", "1000", 0));
        labRec->setText(QApplication::translate("comPortClass", "Receive port", 0));
        label->setText(QString());
        label_2->setText(QString());
        label_3->setText(QString());
        label_4->setText(QString());
        labTemper->setText(QApplication::translate("comPortClass", "Temperature", 0));
        labHumidity->setText(QApplication::translate("comPortClass", "Humidity", 0));
        labLight->setText(QApplication::translate("comPortClass", "Light", 0));
        labCoding->setText(QApplication::translate("comPortClass", "Coding", 0));
        labCoding2->setText(QApplication::translate("comPortClass", "Coding", 0));
        btnExit->setText(QApplication::translate("comPortClass", "EXIT", 0));
        labVibration->setText(QApplication::translate("comPortClass", "Vibration", 0));
        labSmoke->setText(QApplication::translate("comPortClass", "Smoke", 0));
        labInfrared->setText(QApplication::translate("comPortClass", "Infrared", 0));
        labInTouche->setText(QApplication::translate("comPortClass", "Touch", 0));
        labInWave->setText(QApplication::translate("comPortClass", "Wave", 0));
        btnRunType1->setText(QApplication::translate("comPortClass", "Heat dissipation", 0));
        btnRunType0->setText(QApplication::translate("comPortClass", "STOP", 0));
        btnRunType2->setText(QApplication::translate("comPortClass", "Indoor lighting", 0));
        labCom_2->setText(QApplication::translate("comPortClass", "Rate:", 0));
        labCom_3->setText(QApplication::translate("comPortClass", "DataBits:", 0));
        btnExit_2->setText(QApplication::translate("comPortClass", "About", 0));
        labLight_2->setText(QApplication::translate("comPortClass", "Manache", 0));
        labLight_3->setText(QApplication::translate("comPortClass", "Light", 0));
        labManStatus->setText(QApplication::translate("comPortClass", "STOP", 0));
        labLight_5->setText(QApplication::translate("comPortClass", "IOT 13-1 Han Shukai", 0));
        btnRunType3->setText(QApplication::translate("comPortClass", "Smoke Warning", 0));
        checkHeat->setText(QString());
        checkLight->setText(QString());
        checkSmoke->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class comPortClass: public Ui_comPortClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_COMPORT_H
